Repository san-ghun/minishell, pull requests merged in 2023-09, with the labels that each got.

#55 Feat/update parsecmd
  .gitignore
  include/minishell.h
  src/parsecmd.c
  src/parsecmd/parsecmd.c
  src/parsecmd/parsecmd_tokenize.c
  src/t_sent/sent_add.c
  src/util/ft_isspace.c
  src/util/ft_strndup.c
Labels: enhancement

#56 Feat/update parsecmd
  Makefile
  include/minishell.h
  src/minishell.c
  src/parsecmd/parsecmd.c
  src/parsecmd/parsecmd_util.c
Labels: enhancement

#58 [fix] `t_env` based on feedback
  include/minishell.h
  src/built-in/ft_env.c
  src/minishell.c
  src/t_env/env_add.c
  src/t_env/env_del.c
  src/t_env/env_init.c
  test.c
Labels: documentation, enhancement

#59 feat: Update expanding of dallar and tilde for parsecmd
  include/minishell.h
  src/minishell.c
  src/parsecmd/parsecmd.c
  src/parsecmd/parsecmd_util.c
Labels: enhancement

#60 Feat/prepare parsecmd+pipe
  include/minishell.h
  src/deque/deque_delete.c
  src/minishell.c
  src/minishell_util.c
  src/parsecmd/parsecmd.c
  src/parsecmd/parsecmd_util.c
  src/t_sent/sent_create.c
  src/t_sent/sent_delete.c
  src/t_sent/sent_util.c
Labels: enhancement

#61 Feat/built-in (cd ,echo, env, pwd | working on)
  include/minishell.h
  src/built-in/ft_cd.c
  src/built-in/ft_echo.c
  src/built-in/ft_env.c
  src/t_env/env_del.c
  src/t_env/env_init.c
  src/t_env/env_util.c
  test.c
Labels: enhancement

#62 Feat/builtin
  include/minishell.h
  src/built-in/dispatchcmd.c
  src/built-in/ft_cd.c
  src/built-in/ft_echo.c
  src/built-in/ft_env.c
  src/built-in/ft_export.c
  src/t_env/env_add.c
  src/t_env/env_util.c
  test.c
Labels: enhancement

#63 feat: Update executecmd to work with built-in functions
  Makefile
  include/minishell.h
  src/executecmd/executecmd.c
  src/minishell.c
  test.c
Labels: enhancement

#69 feat: Fix memory leak from path finding
  include/minishell.h
  src/built-in/ft_env.c
  src/executecmd/executecmd.c
  src/executecmd/executecmd_util.c
  src/executecmd/runheredoc.c
  src/minishell_util.c
Labels: bug

#70 feat: Fix memory leak from path checking
  include/minishell.h
  src/executecmd/executecmd.c
  src/executecmd/executecmd_check.c
  src/executecmd/executecmd_util.c
  src/minishell_util.c
Labels: enhancement

#75 Fix/memoryleak redi+heredoc
  Makefile
  include/minishell.h
  src/executecmd/executecmd.c
  src/executecmd/executecmd_handler.c
  src/executecmd/executecmd_util.c
  src/executecmd/runheredoc.c
  src/executecmd/runredi.c
  src/minishell.c
  src/parsecmd/parsecmd_tosent.c
  src/pipex.c
  src/t_sent/sent_delete.c
Labels: bug, enhancement
